### ISSUE TITLE
Replace STOMP with qpid_proton

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-messaging#32]
The [qpid_proton gem](https://github.com/apache/qpid-proton/tree/master/ruby) should be a better backend for artemis than STOMP, should investigate switching to it.

**Comment by bzwei** [comment]
We had originally the intention to add a qpid implementation but it was halt due to the lacking of resources.
I would not say we want to replace STOMP. We can simply add a new protocol while leave STOMP as a choice.

**Comment by gtanzillo** [comment]
Closing because Artemis is no longer on the roadmap
