### ISSUE TITLE
Kafka subscribe_messages doesn't work for 2 topics

### ISSUE THREAD

**Issue by Ladas** [ManageIQ/manageiq-messaging#38]
Have we tried manageiq-messaging Kafka subscribe_messages, with 2 different topics? When I add another consumer, that would read from a different topic, it just gets stuck, is uses the same consumer group `manageiq_messaging_queue_group`.

Shouldn't the consumer group name be built as `"manageiq_messaging_queue_group_#{topic_name}"` ?

**Comment by Ladas** [comment]
cc @bzwei

**Comment by Ladas** [comment]
@bzwei ping

**Comment by agrare** [comment]
A fix for this issue has been release in v0.1.3 https://github.com/ManageIQ/manageiq-messaging/releases/tag/v0.1.3
