### ISSUE TITLE
Support retry on exception

### ISSUE THREAD

**Issue by bzwei** [ManageIQ/manageiq-messaging#5]
We want to catch a retry specific exception and requeue (likely create another message with the same payload).

**Comment by kbrock** [comment]
We can either catch the exception or just drop it all together

**Comment by bzwei** [comment]
Any uncaught exception can cause the consumer thread disconnect from the message bus. The message can be redelivered if the message is never acked. 

Here we talk about a use case that the consumer purposely throws a `RetryException` (a class to be created), our messaging client catches it and requeues the message for future retry. Therefore the `RetryException` should contain a retry interval.

**Comment by bzwei** [comment]
No intention to implement it anytime soon. Closing.
